name: basic compilation test
run-name: ${{ github.actor }} basic compilation test ⚗️
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ gcc, clang ]
    steps:
      - name: add missing packages
        uses: ConorMacBride/install-package@v1
        with:
          apt: uthash-dev libyang2-dev libsysrepo-dev
      - name: checkout
        uses: actions/checkout@v4
      - name: make
        run : CC=${{ matrix.compiler }} make -j $(nproc)
      - name: basic check
        run : ldd onmcli
